services:
 #Redisコンテナ設定
 redis:
    image: redis:latest
    container_name: redis-db
    ports: 
      - "6379:6379"

#Spring Bootアプリ設定
 app:
   build: .
   container_name: spring-app
   ports:
     - "8080:8080"
   depends_on:
     - redis #redisが先に立ち上がるように設定
   environment:
     #Spring BootにRedisの場所を教えてあげる
     SPRING_DATA_REDIS_HOST: redis
     SPRING_DATA_REDIS_PORT: 6379
